import Foundation
#if canImport(System)
import System
#else
import SystemPackage
#endif

enum AccountStore {
    static func write(paths: Paths, email: String, imap: String, password: String) throws {
        let fm = FileManager.default
        try fm.createDirectory(
            at: URL(fileURLWithPath: paths.directory.string),
            withIntermediateDirectories: true
        )

        let passPath = paths.passFile(email: email)
        let passURL = URL(fileURLWithPath: passPath.string)
        try Data(password.utf8).write(to: passURL, options: .atomic)
        try fm.setAttributes(
            [.posixPermissions: 0o600],
            ofItemAtPath: passPath.string
        )

        let config = himalayaTOML(email: email, imap: imap, passFile: passPath)
        try Data(config.utf8).write(
            to: URL(fileURLWithPath: paths.himalayaConfig.string),
            options: .atomic
        )

        let err = FileHandle.standardError
        err.write(Data("olive-mail account add: stored \(email) → \(passPath)\n".utf8))
        err.write(Data("olive-mail account add: Himalaya config → \(paths.himalayaConfig)\n".utf8))
    }

    static func himalayaTOML(email: String, imap: String, passFile: FilePath) -> String {
        """
        # Generated by olive-mail account add. Password is not in this file.

        [accounts.\(tomlQuote(email))]
        default = true
        email = \(tomlQuote(email))
        mailbox.alias.inbox = "INBOX"

        imap.server = \(tomlQuote(imap))
        imap.sasl.plain.username = \(tomlQuote(email))
        imap.sasl.plain.passwd.command = ["/bin/cat", \(tomlQuote(passFile.string))]

        # No smtp block: bots must not send.

        """
    }

    static func tomlQuote(_ value: String) -> String {
        let escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }
}
