import Foundation
#if canImport(System)
import System
#else
import SystemPackage
#endif

enum AccountStore {
    /// Accepts `imaps://host[:port]`, `imap://host[:port]`, or a bare `host[:port]`.
    /// Himalaya treats a bare authority as `imaps://`. Missing port is 993
    /// (`imaps` / bare) or 143 (`imap`).
    static func normalizeImap(_ raw: String) -> String {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        let scheme: String?
        let rest: String
        if let sep = trimmed.range(of: "://") {
            scheme = String(trimmed[trimmed.startIndex..<sep.lowerBound]).lowercased()
            rest = String(trimmed[sep.upperBound...])
        } else {
            scheme = nil
            rest = trimmed
        }
        if scheme == "unix" { return "unix://" + rest }
        let port = (scheme == "imap") ? 143 : 993
        let authority = withDefaultPort(rest, port)
        if let scheme { return scheme + "://" + authority }
        return authority
    }

    private static func withDefaultPort(_ authority: String, _ port: Int) -> String {
        if authority.hasPrefix("[") {
            guard let close = authority.firstIndex(of: "]") else { return authority }
            let after = authority[authority.index(after: close)...]
            if after.hasPrefix(":") { return authority }
            return authority + ":\(port)"
        }
        if authority.contains(":") { return authority }
        if authority.isEmpty { return authority }
        return authority + ":\(port)"
    }

    static func write(paths: FilePaths, email: String, imap: String, password: String) throws {
        let fm = FileManager.default
        try fm.createDirectory(
            at: URL(fileURLWithPath: paths.directory.string),
            withIntermediateDirectories: true
        )

        let passPath = paths.passFile(email: email)
        let passURL = URL(fileURLWithPath: passPath.string)
        try Data(password.utf8).write(to: passURL, options: .atomic)
        try fm.setAttributes(
            [.posixPermissions: 0o600],
            ofItemAtPath: passPath.string
        )

        let config = himalayaTOML(
            email: email,
            imap: normalizeImap(imap),
            passFile: passPath
        )
        try Data(config.utf8).write(
            to: URL(fileURLWithPath: paths.himalayaConfig.string),
            options: .atomic
        )
    }

    static func himalayaTOML(email: String, imap: String, passFile: FilePath) -> String {
        """
        # Generated by olive-mail account add. Password is not in this file.

        [accounts.\(tomlQuote(email))]
        default = true
        email = \(tomlQuote(email))

        imap.server = \(tomlQuote(imap))
        imap.sasl.plain.username = \(tomlQuote(email))
        imap.sasl.plain.passwd.command = ["/bin/cat", \(tomlQuote(passFile.string))]

        # No smtp block: bots must not send.

        """
    }

    static func tomlQuote(_ value: String) -> String {
        let escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }
}
